// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asfzrlhpradpnkgziwjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzZnpybGhwcmFkcG5rZ3ppd2pjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1ODYyNjcsImV4cCI6MjA2ODE2MjI2N30.uO_i-0NyjbOFFVIp0-YRu9pRqIstpbf2lJ6ABk8_okc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});